### ISSUE TITLE
Problem with debugger Process failed: spawn rdebug-ide ENOENT

### ISSUE THREAD

**Issue by CharlesPL** [rebornix/vscode-ruby#15]
### Your environment

- `vscode-ruby` version: 0.3.1
- Ruby version: ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
- VS Code version: 
- Operating System: Apricity OS
- Hardware (optional): 

Make sure you have `ruby`, `ruby-debug-ide` and `ruby-debug-basex19` installed before submitting your issue -- thank you !

### Actual behavior
When I try to debug a rb file I receive following message
 Debugger terminal error: Process failed: spawn rdebug-ide ENOENT
I'm receiving also this warning while I'm trying to install gems 
WARNING:  You don't have /root/.gem/ruby/2.3.0/bin in your PATH,
	  gem executables will not run.

**Comment by rebornix** [comment]
From what the error message tells, you don't have ruby in your PATH. Since you can add it manually like

```
export PATH="/root/.gem/ruby/2.3.0/bin:$PATH"
source ~/.profile # take effect immediately
```
