### ISSUE TITLE
ARGV[0] returning 'undefined' instead of expected nil

### ISSUE THREAD

**Issue by betancourtcaupmc** [rebornix/vscode-ruby#19]
### Your environment

- `vscode-ruby` version: 0.3.3
- Ruby version: 2.2.4p230
- VS Code version: 1.0.0
- Operating System: windows 10
- Hardware (optional): 

Make sure you have `ruby`, `ruby-debug-ide` and `ruby-debug-basex19` installed before submitting your issue -- thank you !

given this code

indexName = ARGV[0] || 'indexName'
typeName = ARGV[1] || 'typeName'
sourceFilename = ARGV[2] ||  'sourceFileName'
puts "     indexName: #{indexName}"
puts "      typeName: #{typeName}"
puts "sourceFilename: #{sourceFilename}"

### Expected behavior

     indexName: indexName
      typeName: typeName
sourceFilename: sourceFileName

### Actual behavior
     indexName: undefined
      typeName: typeName
sourceFilename: sourceFileName

### Steps to reproduce the problem
running included code through the commandline: ruby filename.rb works  as expected
running debugging code through visualstudiocode ARGV[0] returns 'undefined' instead of nil.
to reproduce add ARGV[0], ARGV[1], ARGV[2] to watches...

**Comment by HookyQR** [comment]
Hey @betancourtcaupmc. I've submitted a fix for this. Should go in once @rebornix has checked, merged, updated versions and published. 😉

**Comment by rebornix** [comment]
Just came back from vacation. Release 0.3.4.
