### ISSUE TITLE
Trouble passing arguments to script

### ISSUE THREAD

**Issue by bretjensen** [rebornix/vscode-ruby#22]
### Your environment

- `vscode-ruby` version: 0.3.4
- Ruby version: 1.9.3
- VS Code version: 1.1.0
- Operating System: Windows 10
- Hardware (optional):

Make sure you have `ruby`, `ruby-debug-ide` and `ruby-debug-basex19` installed before submitting your issue -- thank you !

### Expected behavior
I am trying to pass arguments to my script when running main.rb in debug mode and having trouble getting anything.

I am trying to capture them with ARGV array but it keeps coming in as empty. I thought at first to use the args array in the launch.json file, but realised this was passing parameters to the debugger.

### Actual behavior

I have tried using the reuntimeArgs: node to read in my runtime parameters, but the array read by ARGV is always empty.

It's more about how to pass runtime script parameters into the ruby script to be picked up by ARGV?
` {        
            "name": "Debug Local File",
            "type": "Ruby",
            "request": "launch",
            "program": "${workspaceRoot}/main.rb",`

I have tried 
`"runtimeArgs": [
  "--MyParam1 testvalue1",
  "--MyParam2 testvalue2"
]`

I have tried 
`"runtimeArgs": [
  "--MyParam1 testvalue1 --MyParam2 testvalue2"
]`

And I have tried
`"runtimeArgs": [
  "--MyParam1", 
  "testvalue1",
  "--MyParam2", 
  "testvalue2"
]`
### Steps to reproduce the problem

Can you please give me an indication of how to pass these parameters to the main.rb

Thanks
Brett

**Comment by HookyQR** [comment]
Hi @bretjensen, to pass arguments to your process, use the `args` setting rather than `runtimeArgs`. RuntimeArgs are placed before your script name in the command line that calls the debugger. Args are placed after. If you have any dashed arguments that may conflict with the settings of `rdebug-ide` pass `--` as the first argument.

In short, change your launcher to:

```json
{
  "name": "Debug Local File", 
  "type": "Ruby", 
  "request": "launch", 
  "program": "${workspaceRoot}/main.rb",
  "args": [ "--", "--MyParam1", "testvalue1", "--MyParam2", "testvalue2" ]
}
```
