### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by spagidipati** [rebornix/vscode-ruby#3]
Sorry, may be I am too early while this extension seems like in test phase, I am getting error as below (Ruby 1.9.3 p551), on windows 7 x64 ent.
spawn rdebug-ide ENOENT
Debugger client error, Error: This socket is closed.
also tried with Ruby 2.0 or 2.2 with x64, cannot install ruby-debug-base19x 

Thanks for the help.

**Comment by rebornix** [comment]
Thanks @spagidipati for your trail and reporting this issue. As I'm focusing on the development for now, I haven't got enough time to test against multi platform and ruby versions, your help can make this extension more mature.

If I interpret your words right, you are running into two failed cases
1. Install Ruby 1.9.3 p551 and `ruby-debug-ide`, `ruby-debug-base19x` on Windows 7 x64. But when you try to debug your ruby scripts, it throws `spawn rdebug-ide ENOENT Debugger client error, Error: This socket is closed.`, right? If so, can you provide the scripts you are debugging with or a tiny script that can help reproduce this bug?
2. You try to install Ruby 2.0 or 2.2 on your Windows 7 x64 machine, but failed to install gem `ruby-debug-base19x`.

It would be great if you can provide more detailed information and thanks in advance!

**Comment by rebornix** [comment]
@spagidipati  you can also take a look at the installation instruction I added today from https://github.com/rebornix/vscode-ruby#install-ruby-dependencies , let me know if it helps you out.

**Comment by spagidipati** [comment]
thanks for the reply, I am newbie to Ruby! so Instead of using eclipse
thought of using VS Code.In the first case I chose the Ruby Version 1.9.3
p551. and I am using the same script as is specified in instructions .
when I start debugging , all debugging navigation is disabled and only STOP
button is enabled and on left side panel below "Ruby Debug" settings icon
you can see the blue progress indefinitely scrolls horizontally and nothing
happens.

[image: Inline image 1]

after stopping the debugging , you can see the error message

[image: Inline image 2]

my launch.json settings

[image: Inline image 3]

Thanks
Suresh

**Comment by rebornix** [comment]
@spagidipati seems you replying from Email but all the image links are broken, would you mind edit your comment in GitHub site then I can see the images? thanks!

**Comment by rebornix** [comment]
@spagidipati I reproduced this bug on my windows devbox successfully and give it a quick fix, now you can download the latest version `v0.1.8` and play with it, the error should be gone!

**Comment by spagidipati** [comment]
thanks!, it is now working.

**Comment by matthewblott** [comment]
I'm afraid I a have this error too. I've followed the instructions and installed the dependencies. I'm trying a very trivial example (print 'hello' to the console). 
![s 2016-03-08 at 21 10 40](https://cloud.githubusercontent.com/assets/1231417/13616562/457a39b8-e572-11e5-85be-d7bf82a1ec02.jpg)

**Comment by HookyQR** [comment]
@matthewblott, can you please provide details of:
- your operating system, 
- the version of ruby-debug-ide and it's install path, (The command should be either rdebug-ide, or rdebug-ide.bat depending on your operating system)
- your path environment variable, and
- the version of this plugin you're using: (In VS Code: hit `F1`, type `ext` and find the version of Ruby: the version number will be on the right)

From the screen shot you have provided, it looks like the debugger isn't available in your path.

**Comment by rebornix** [comment]
@matthewblott thanks for reporting this issue! Seems you are using Mac and it happens to my dev machine, so it's supposed to have the best support for this extension as I'm always testing against it. Would mind provide your Ruby version by running `ruby -v` and share your gem list by `gem list`, thanks!

**Comment by matthewblott** [comment]
Ruby version is 2.3.0 and here's the gem list ...

actioncable (5.0.0.beta2, 5.0.0.beta1.1, 5.0.0.beta1)
actionmailer (5.0.0.beta2, 5.0.0.beta1.1, 5.0.0.beta1, 4.2.5.1)
actionpack (5.0.0.beta2, 5.0.0.beta1.1, 5.0.0.beta1, 4.2.5.1)
actionview (5.0.0.beta2, 5.0.0.beta1.1, 5.0.0.beta1, 4.2.5.1)
activejob (5.0.0.beta2, 5.0.0.beta1.1, 5.0.0.beta1, 4.2.5.1)
activemodel (5.0.0.beta2, 5.0.0.beta1.1, 5.0.0.beta1, 4.2.5.1)
activerecord (5.0.0.beta2, 5.0.0.beta1.1, 5.0.0.beta1, 4.2.5.1)
activesupport (5.0.0.beta2, 5.0.0.beta1.1, 5.0.0.beta1, 4.2.5.1)
addressable (2.4.0)
arel (7.0.0, 6.0.3)
bigdecimal (1.2.8)
builder (3.2.2)
bundle (0.0.1)
bundler (1.11.2)
byebug (8.2.2, 8.2.1)
celluloid (0.17.3)
celluloid-essentials (0.20.5)
celluloid-extras (0.20.5)
celluloid-fsm (0.20.5)
celluloid-pool (0.20.5)
celluloid-supervision (0.20.5)
coffee-rails (4.1.1)
coffee-script (2.4.1)
coffee-script-source (1.10.0)
colorator (0.1)
concurrent-ruby (1.0.0)
debase (0.2.1)
debase-ruby_core_source (0.8.4)
debug_inspector (0.0.2)
did_you_mean (1.0.0)
em-hiredis (0.3.1, 0.3.0)
erubis (2.7.0)
eventmachine (1.0.9.1)
execjs (2.6.0)
fastimage (1.8.1)
faye-websocket (0.10.2)
ffi (1.9.10)
globalid (0.3.6)
hiredis (0.6.1, 0.5.2)
hitimes (1.2.3)
i18n (0.7.0)
io-console (0.4.5)
jbuilder (2.4.0)
jekyll (3.0.2)
jekyll-assets (2.1.2)
jekyll-lunr-js-search (3.0.0)
jekyll-sass-converter (1.4.0)
jekyll-watch (1.3.1)
jquery-rails (4.1.0)
json (1.8.3)
kramdown (1.9.0)
libv8 (3.16.14.13)
liquid (3.0.6)
listen (3.0.5)
loofah (2.0.3)
mail (2.6.3)
mercenary (0.3.5)
method_source (0.8.2)
mime-types (2.99)
mini_magick (4.3.6)
mini_portile2 (2.0.0)
minitest (5.8.4, 5.8.3)
multi_json (1.11.2)
net-telnet (0.1.1)
nio4r (1.2.1)
nokogiri (1.6.7.2)
power_assert (0.2.6)
psych (2.0.17)
puma (2.16.0, 2.15.3)
rack (2.0.0.alpha, 1.6.4)
rack-test (0.6.3)
rails (5.0.0.beta2)
rails-deprecated_sanitizer (1.0.3)
rails-dom-testing (1.0.7)
rails-html-sanitizer (1.0.3, 1.0.2)
railties (5.0.0.beta2, 5.0.0.beta1.1, 5.0.0.beta1, 4.2.5.1)
rake (10.5.0, 10.4.2)
rb-fsevent (0.9.7)
rb-inotify (0.9.5)
rdoc (4.2.1)
redis (3.2.2)
ref (2.0.0)
rouge (1.10.1)
ruby-debug-ide (0.6.0)
safe_yaml (1.0.4)
sass (3.4.21)
sass-rails (5.0.4)
spring (1.6.2)
sprockets (3.5.2)
sprockets-helpers (1.2.1)
sprockets-rails (3.0.1, 3.0.0)
sqlite3 (1.3.11)
test-unit (3.1.5)
therubyracer (0.12.2)
thor (0.19.1)
thread_safe (0.3.5)
tilt (2.0.2)
timers (4.1.1)
turbolinks (2.5.3)
tzinfo (1.2.2)
uglifier (2.7.2)
web-console (3.1.1, 3.0.0)
websocket-driver (0.6.3)
websocket-extensions (0.1.2)

**Comment by rebornix** [comment]
Unfortunately I can't repro this issue, that's really weird. Can you help run following commands in your terminal to help us troubleshoot:

1.  Open the working folder of the ruby scripts (your main.rb) in your terminal, run `kill -9 $(lsof -ti:1234) & rdebug-ide test.rb -xd`
2. Open another terminal window, run `telnet 127.0.0.1 1234`

Then tell us what's the output of them, thanks :+1:

**Comment by matthewblott** [comment]
![s 2016-03-10 at 16 37 28](https://cloud.githubusercontent.com/assets/1231417/13676615/7b746dbe-e6de-11e5-8330-a8938047ed9e.jpg)
![s 2016-03-10 at 16 37 33](https://cloud.githubusercontent.com/assets/1231417/13676624/814bfe14-e6de-11e5-8ee1-22d2750f05da.jpg)
![s 2016-03-10 at 16 37 39](https://cloud.githubusercontent.com/assets/1231417/13676626/83f11050-e6de-11e5-9f2d-822b9effff00.jpg)

**Comment by HookyQR** [comment]
No problem.
