### ISSUE TITLE
ES7 methods and XMLDom error handling breaks SERVER MODE

### ISSUE THREAD

**Issue by rebornix** [rebornix/vscode-ruby#7]
The code runs perfectly in extension mode or test pipeline, but if you try to develop in server mode, in which case you can set breakpoints to the debugger adapter, it breaks as below

![](http://7sbn7z.com5.z0.glb.clouddn.com/server-mode-broken.gif)

seems currently server mode doesn't have a good support for ES7 methods.

BTW, even if I convert these methods to ES5 style, Variables are missing, it's likely a bug.

**Comment by rebornix** [comment]
@HookyQR would you take a look at this issue as it breaks current development process.

**Comment by HookyQR** [comment]
Try changing all of the `includes()` to `indexOf() >= 0`. I don't have time tonight to look. Let me know if it's not better by the same time tomorrow. Seems like the compile from typescript might be off. Perhaps there is an issue with the node version you have installed outside of VS Code.

**Comment by rebornix** [comment]
@HookyQR Besides `includes`, we have problem with `startsWith`, `endsWith` either. My local node version is `4.1.1` installed by `nvm`, so it should be the same with CI otherwise `npm test` can't pass. The bigger problem is variable inspection doesn't work in development mode.

No hurries, just take your time. Before developing features for Rails, I'd like adding more cases improve the code coverage, it can be done without debugging maybe.

**Comment by HookyQR** [comment]
Can you tell me how you're running the server and client together. I can't get the server debugger to be called.

**Comment by rebornix** [comment]
You can refer to this article for its setup https://code.visualstudio.com/docs/extensions/example-debuggers#_development-setup-for-mockdebug . This topic describes the extendion mode and server mode perfectly.

For short, instead of run `Launch Extendion`, you should run `Mock debug server`. Then launch another VS Code Window,  open the test project, put `"debugServer": 4711,` in launch.json . 

Lastly, take a look at this issue for how to debug Debugger Adapter while running mocha test cases https://github.com/Microsoft/vscode/issues/3144#event-581794537

**Comment by HookyQR** [comment]
I am unable to recreate the issue. Can you provide an enumeration of 
`JSON.stringify(_this.domErrors)` when the exception is raised. Mine has:

```
"[{"lineNumber":1,"columnNumber":8,"error":"[xmldom warning]\tunclosed xml attribute\n@#[line:1,col:8]","type":"warning"}]"
```

I think that the `error` attribute is not being set to a string some how.

**Comment by rebornix** [comment]
My output is similar to yours 

```
"[{"lineNumber":1,"columnNumber":9,"error":"[xmldom warning]\tunclosed xml attribute\n@#[line:1,col:9]","type":"warning"}]"
```

Have you ever try converting all these ES7 methods to ES5 ones and run ?

**Comment by rebornix** [comment]
Weird, the error is gone when I changed them to ES5 functions. I'll update the code and close this issue. Thanks for your help Bryan.

**Comment by HookyQR** [comment]
@rebornix: Changing the ES7 functions hasn't changed anything. I still have them all as the original here and have no problems. Node 4+ can use them out of the box, so the issue isn't that. Doesn't mean I know what it was though. :wink:
