### ISSUE TITLE
Error when start debugger:

### ISSUE THREAD

**Issue by magicwhite** [rebornix/vscode-ruby#9]
### Your environment
Mac OSX 
- `vscode-ruby` version:  plugin version 0.3.0
- System: Mac OSX el cap
- Ruby version: 2.2.0
- Hardware(optional): macbook pro 13'

Make sure you have `ruby`, `ruby-debug-ide` and `ruby-debug-basex19` installed before submitting your issue -- thank you !

### Expected behavior
start debugger

### Actual behavior
Debugger error: Client: Error: getaddrinfo ENOTFOUND localhost undefined:1234
### Steps to reproduce the problem

![vscode](https://cloud.githubusercontent.com/assets/8948783/13809217/9bf5ab32-eba4-11e5-9586-5465a653226f.png)

**Comment by magicwhite** [comment]
when I start rdebug-ide in a terminal then using remote debug listener, it is OK. But Debug local file failed.

**Comment by rebornix** [comment]
@magicwhite can you share your launch. json with me?

**Comment by magicwhite** [comment]
Sure.
![lunch](https://cloud.githubusercontent.com/assets/8948783/13817428/19b7c028-ebcd-11e5-9054-1bf7785e7770.png)

**Comment by HookyQR** [comment]
Hi @magicwhite, the internal debugger connects to localhost rather than 127.0.0.1, and the error you are showing looks like your net setup isn't resolving localhost properly. To determine if that is the issue, can you please change the remoteHost value in your launch settings for the `attach` process to `localhost` and check if running as remote debug still works.

**Comment by magicwhite** [comment]
Hi @HookyQR thanks you very mach. It is because my Mac can't resolving` localhost` properly.
I checked my `/etc/hosts` file and add modified it as:
```
# Host database
#
# localhost is used to configure the loopback interface
# when the system is booting. Do not change this entry.
##
127.0.0.1       localhost
255.255.255.255 boardcasthost
```
It works good now. thanks a lot.
